import Header from '../components/Header'
import Navbar from '../components/Navbar'
import { useState } from 'react'
import Footer from '../components/Footer'
import Head from 'next/head'
import BackDrop from '../components/BackDrop'
import Script from 'next/script'

function MyApp({ Component, pageProps }) {
  const [toggle, setToggle] = useState(false);

  return (
    <>
      <Head>
        <title>Moon Night Group</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/assets/img/favicon.ico" />

      </Head>
      <Script src="assets/js/bootstrap.min.js"></Script>
      <Header />
      <Navbar show={toggle} click={() => setToggle(!toggle)} />
      <BackDrop show={toggle} click={() => setToggle(false)} />
      <Component {...pageProps} />
      <Footer />
    </>

  )
}

export default MyApp
