import Header from '../components/Header'
import Navbar from '../components/Navbar'
import '../styles/globals.css'
import '../public/assets/css/classy-nav.min.css'
import '../public/assets/css/style.css'
import '../public/assets/css/bootstrap.min.css'
import '../public/assets/css/animate.css'
import '../public/assets/css/font-awesome.min.css'
import '../public/assets/css/magnific-popup.css'
import '../public/assets/css/icofont.css'
import '../public/assets/css/classy-nav.min.css'
import '../public/assets/css/gallery-slider.css'
import '../public/assets/css/style.css'
import '../public/assets/css/responsive.css'
import '../public/assets/css/color/color-default.css'
import '../public/assets/dist/color-switcher.css'
import Footer from '../components/Footer'
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  
  return (

    <>
     <Head>
        <title>Moon Night Group</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/assets/img/favicon.ico" />
      </Head>
      <Header />
      <Navbar/>
      <Component {...pageProps} />
      <Footer/>
    </>

  )
}

export default MyApp
