import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Homes from './home'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moon Night Group</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      
      </Head>
    
        <Homes />
    

      <footer className={styles.footer}>
       
      </footer>

    </div>
  )
}
